version: '3'

services:
    my-postgres-server:
        image: 'postgres:latest'
        environment: 
            - POSTGRES_PASSWORD=${PGPASSWORD}
    my-redis-server:
        image: 'redis:latest'
    my-backend:
        build:
            dockerfile: dockerfile.dev
            context: ./backend
        volumes: 
            - /opt/app/node_modules
            - ./backend:/opt/app
        ports:
            - '5000:5000'
        environment: 
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PORT=${REDIS_PORT}
            - PGHOST=${PGHOST}
            - PGUSER=${PGUSER}
            - PGDATABASE=${PGDATABASE}
            - PGPASSWORD=${PGPASSWORD}
            - PGPORT=${PGPORT}
    my-frontend:
        build: 
            dockerfile: dockerfile.dev
            context: ./frontend
        volumes: 
            - /opt/app/node_modules
            - ./frontend:/opt/app
        tty: true
        ports:
            - '3000:3000'
    my-nginx:
        restart: always
        build:
            dockerfile: dockerfile.dev
            context: ./nginx
        ports:
            - '8080:80'