kubectl delete ingress my-ingress-project-service
kubectl delete svc my-frontend-project-service
kubectl delete deploy my-frontend-project-deployment
kubectl delete svc my-backend-project-service
kubectl delete deploy my-backend-project-deployment
kubectl delete svc my-postgres-project-service
kubectl delete deploy my-postgres-project-deployment
kubectl delete secret my-postgres-project-secret
kubectl delete svc my-redis-project-service
kubectl delete deploy my-redis-project-deployment
kubectl delete configmap myapp-project-configmap
