apiVersion: v1

kind: Service

metadata:
  name: my-frontend-project-service

spec:
  type: NodePort
  ports:
    - targetPort: 3000
      port: 3000
      nodePort: 30009

  selector:
    app: my-frontend
    type: frontend
