apiVersion: apps/v1

# rodzaj bytu jaki tworzymy
kind: ReplicaSet

#dostarcza opis
metadata:
    name: myapp-rs
    labels:
        app: myapp
        type: frontend

#okresla dokladnie byt ktory definiujemy
spec:
    template:
        metadata:
            name: myapp-pod
            labels:
                app: myapp
                type: frontend

        spec:
            containers:
                - name: my-nginx-container
                  image: nginx
    replicas: 6
    selector:
        matchLabels:
            type: frontend